# sensors/hardware
all_components: 1
# simulator: 0      # simulator may publish its own urdf or launch rviz, please check your setting in sim.yaml.

# camera navigation
# camera_nav_calibration: 0
# camera_nav: 0

# slam-toolbox
slam: 0

## nav2
map: 0                    # - map_server
localization: 0           # - localization_server
# ekf: 0                    # - ekf sensor fusion from robot_localization pkg
# odom_rf2o: 0              # - rf2o laser odometry
# planner: 0                # - Path Planner (Real-Time planner). Nav2 Local Planner.

# recording data 
rosbag_launch: 0
ros_bridge_launch: 0

## Foxglove Studio
# rosbridge_suite: 0

# TODO: Obstacle Avoidance
# simple_obstacle_detection_launch: 0

# rviz
sensor_visualization: 1

# Wall Following
# wall_follow: 0

# control
# f1tenth_vesc_joy_launch: 0
# pid_launch: 0
# lqr_launch: 0
# lqg_launch: 0
# lqg_w_launch: 0
# mpc_launch: 0

# path planner
# path_nav: 0
# tube_follower_launch: 0
# curve_localizer_launch: 0

urdf: 0

pointcloud_to_laserscan: 0

# scan_correction: 0
